baseUrl: $DEFAULT_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Starter'
primary: false
siteGroup: 8f9e36f4-7d7b-41d7-830a-e3441bfaedbe # Craft Starter
sortOrder: 1
