contentColumnType: string(720)
fieldGroup: a3e39be1-6cc6-4282-8292-b85308af9a68
handle: head
instructions: ''
name: Head
searchable: false
settings:
  byteLimit: null
  charLimit: 180
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
