contentColumnType: boolean
fieldGroup: 1379c320-6760-4c1b-8dad-51ec73c3cd8b
handle: toggleAwsImageProcessor
instructions: null
name: 'Toggle aws image processor'
searchable: false
settings:
  default: true
translationKeyFormat: null
translationMethod: none
type: dutchheight\awsserverlessimagehandler\fields\ImageProperties
