enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  4e2c308a-d0d1-4ad6-9a24-9c451efa5d3f:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: __home__
type: single
